"""add activity entry and activity event tables

Revision ID: f612a25bd54d
Revises: b7c41d9e2f08
Create Date: 2026-09-16 13:42:49.864486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f612a25bd54d'
down_revision: Union[str, Sequence[str], None] = 'b7c41d9e2f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_events_public_created_at_id'), table_name='feed_events', postgresql_where='(is_public = true)')
    op.create_index('ix_feed_events_public_created_at_id', 'feed_events', ['created_at', 'id'], unique=False, postgresql_where=sa.text('is_public = true'))
    op.drop_index(op.f('ix_live_projects_visible_feed'), table_name='live_projects', postgresql_where='((is_public = true) AND (is_draft = false))')
    op.create_index('ix_live_projects_visible_feed', 'live_projects', ['created_at', 'id'], unique=False, postgresql_where=sa.text('is_public = true AND is_draft = false'))
    op.drop_index(op.f('ix_project_comments_visible_thread'), table_name='project_comments', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_project_comments_visible_thread', 'project_comments', ['project_id', 'parent_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_comments_visible_thread', table_name='project_comments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_project_comments_visible_thread'), 'project_comments', ['project_id', 'parent_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_live_projects_visible_feed', table_name='live_projects', postgresql_where=sa.text('is_public = true AND is_draft = false'))
    op.create_index(op.f('ix_live_projects_visible_feed'), 'live_projects', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where='((is_public = true) AND (is_draft = false))')
    op.drop_index('ix_feed_events_public_created_at_id', table_name='feed_events', postgresql_where=sa.text('is_public = true'))
    op.create_index(op.f('ix_feed_events_public_created_at_id'), 'feed_events', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where='(is_public = true)')
    # ### end Alembic commands ###
